# Generated by Django 2.2.7 on 2019-11-19 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=256)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id_periodoContable', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.TextField()),
                ('anio', models.TextField()),
                ('estadoPeriodo', models.NullBooleanField(default=True)),
                ('saldoInicial', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('tipo', models.CharField(default='otro', max_length=6)),
                ('cuenta_Debe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuenta_Debe', to='core.Cuenta')),
                ('cuenta_Haber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuenta_Haber', to='core.Cuenta')),
                ('cuenta_IVA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuenta_IVA', to='core.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluyeIVA', models.BooleanField(default=False)),
                ('IVA', models.DecimalField(decimal_places=2, default=False, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=256)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoTransaccion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AFP', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AFP')),
                ('ISSS', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ISSS')),
                ('renta', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('salarioBase', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SalarioTotal')),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('salarioNeto', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario Nominal')),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Clase')),
            ],
            options={
                'unique_together': {('codigo', 'clase')},
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('renta', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidades', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Utilildad')),
                ('utilidadNeta', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Utilildad')),
                ('periodo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCapital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capital Contable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPeriodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('saldoDeudor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('saldoAcreedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('cuenta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cuenta')),
                ('periodo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Grupo'),
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceComprobacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='haber')),
                ('periodo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AFP', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AFP')),
                ('ISSS', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ISSS')),
                ('renta', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('salarioBase', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('salarioNeto', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PeriodoContable')),
            ],
            options={
                'unique_together': {('periodo', 'empleado')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('codigo', 'grupo')},
        ),
    ]
