# Generated by Django 2.2.7 on 2019-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entrada_producto_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
