# Generated by Django 2.2.7 on 2019-11-19 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191119_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='extotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
