# Generated by Django 2.2.7 on 2019-11-19 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entrada_extotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='excantidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='extotal',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
