# Generated by Django 2.2.7 on 2019-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='excantidad',
        ),
    ]
