# Generated by Django 2.2.7 on 2019-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191119_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
