# Generated by Django 2.2.7 on 2019-11-19 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191119_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrada',
            name='T',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='empty',
            field=models.BooleanField(default=True),
        ),
    ]
