# Generated by Django 2.2.7 on 2019-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191119_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
