# Generated by Django 3.2.8 on 2021-10-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kardex', '0001_initial'),
        ('transaccionInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionInventario',
            fields=[
                ('idActualzacion', models.AutoField(primary_key=True, serialize=False)),
                ('existencias', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
                ('costoTotal', models.FloatField()),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.kardex')),
                ('transaccionInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccionInventario.transaccioninventario')),
            ],
        ),
    ]
