# Generated by Django 3.2.8 on 2021-10-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('transaccionInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('idKardex', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('existenciaFinal', models.IntegerField()),
                ('saldoFinal', models.FloatField()),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.kardex')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPeriodo',
            fields=[
                ('idLineaPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tipoTransaccion', models.CharField(max_length=3)),
                ('valorUnitario', models.FloatField()),
                ('cantidadEntrada', models.IntegerField()),
                ('valorEntrada', models.FloatField()),
                ('cantidadSalida', models.IntegerField()),
                ('valorSalida', models.FloatField()),
                ('cantidadExistencia', models.IntegerField()),
                ('valorExistencia', models.FloatField()),
                ('comprobacion', models.FloatField()),
                ('cantidadSobrante', models.IntegerField()),
                ('compraAsociada', models.IntegerField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.periodo')),
                ('transaccionInvAsociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccionInventario.transaccioninventario')),
            ],
        ),
    ]
