# Generated by Django 3.2.8 on 2021-10-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombreContribuyente', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=17)),
                ('nrc', models.CharField(max_length=10)),
                ('giro', models.CharField(max_length=30)),
            ],
        ),
    ]
